#!/bin/bash -e

function usage() {
  bold=$(tput bold)
  norm=$(tput sgr0)
 
  echo "usage: $0 [OPTIONS] name[:tag|@digest]" >&2
  echo "" >&2
  echo "-s, --shrink            Remove unneeded files from the container" >&2
  echo "-k, --kernel  PATH      Where to store the extracted kernel" >&2
  echo "-i, --initrd  PATH      Where to store the generated initrd" >&2
  echo "-c, --cmdline PATH      Where to store the extracted cmdline" >&2
  echo "-z, --zip     CMD       The command to use for compressing the initrd" >&2
  echo "" >&2
  echo "NOTE: Requires ${bold}root${norm} or ${bold}buildah unshare${norm}." >&2
  exit 2
}

function unknown() {
  echo "unknown option: $1"
  echo ""
  usage
}

ZIP=cat
while true; do
  case "$1" in
    -s | --shrink) SHRINK=y; shift 1;;
    -k | --kernel) KERNEL=$2; shift 2;;
    -i | --initrd) INITRD=$2; shift 2;;
    -c | --cmdline) CMDLINE=$2; shift 2;;
    -z | --zip) ZIP=$2; shift 2;;
    -h | --help) usage;;
    --) shift; break;;
    --*) unknown $1;;
    -*) unknown $1;;
    *) break;;
  esac
done

shift $((OPTIND-1))
[ -z "$1" ] && usage

# Generate a UUID to avoid collisions.
CNTNR=`cat /proc/sys/kernel/random/uuid`

# Mount the container image.
buildah from --name "$CNTNR" "$1"
export SRC=`buildah mount $CNTNR`

# Setup cleanup traps
function cleanup() {
  buildah unmount $CNTNR
  buildah rm $CNTNR
  rm -f $KERNEL $INITRD
}
trap cleanup EXIT 

# Extract the kernel.
if [ -n "$KERNEL" ]; then
  if [ -f $SRC/boot/wyrcan.kernel ]; then
    cp -P $SRC/boot/wyrcan.kernel "$KERNEL"
  else
    echo "Unable to find /boot/wyrcan.kernel!" >&2
    exit 1
  fi
fi

# Extract the cmdline.
if [ -n "$CMDLINE" ]; then
  if [ -f $SRC/boot/wyrcan.cmdline ]; then
    cp -P $SRC/boot/wyrcan.cmdline "$CMDLINE"
  else
    touch "$CMDLINE"
  fi
fi

# Minimize the container.
if [ -n "$SHRINK" ]; then
  # Remove all kernels.
  rm -f $SRC/vmlinu*
  rm -f $SRC/boot/vmlinu*

  # Remove all initrds.
  rm -f $SRC/initrd.img*
  rm -f $SRC/boot/initrd.img*
fi

# Build the initrd.
if [ -n "$INITRD" ]; then
  (cd $SRC && find . | sort | cpio --quiet -H newc -o) | $ZIP > "$INITRD"
fi

trap - EXIT
buildah unmount $CNTNR
buildah rm $CNTNR
