default:
  image: debian:latest
  tags:
    - linux

build:
  before_script:
    - apt update
    - apt install -y buildah mtools xorriso xz-utils ca-certificates dosfstools libarchive-tools cpio
  script:
    - bash -x ./build.sh build
  artifacts:
    paths:
      - wyrcan.kernel
      - wyrcan.initrd
      - wyrcan.iso
