default:
  tags:
    - linux

fmt:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  needs: []
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

clippy:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  needs: []
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings

debug:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  needs: []
  image: rust:latest
  script:
    - cargo build

release:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  needs: []
  image: rust:latest
  script:
    - cargo build --release
    - mv target/release/wyrcan wyrcan
    - strip ./wyrcan
  artifacts:
    paths:
      - wyrcan

build:
  rules:
    - if: $CI_MERGE_REQUEST_IID
  needs: ["release"]
  image: docker:latest
  services:
    - docker:dind
  script:
    - cp wyrcan container/wyrcan
    - chmod g-w,o-w container/*
    - docker build container/

tag:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  needs: ["release"]
  image: docker:latest
  services:
    - docker:dind
  script:
    - cp wyrcan container/wyrcan
    - chmod g-w,o-w container/*
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME container/
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

images:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  needs: ["release", "tag"]
  image: debian:latest
  before_script:
    - apt update
    - apt install -y mtools xorriso xz-utils ca-certificates dosfstools libarchive-tools cpio
  script:
    - ./wyrcan morph --kernel wyrcan.kernel --initrd wyrcan.initrd.gz $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    - gunzip -c wyrcan.initrd.gz | xz -c -T0 -9 -C crc32 > wyrcan.initrd
    - ./iso.sh wyrcan.kernel wyrcan.initrd wyrcan.iso
  artifacts:
    paths:
      - wyrcan.kernel
      - wyrcan.initrd
      - wyrcan.iso
