default:
  tags:
    - linux

stages:
  - cargo
  - container
  - images

fmt:
  stage: cargo
  image: rust:1.56.1
  before_script:
    - rm rust-toolchain.toml
    - rustup component add rustfmt
  script:
    - RUSTC_BOOTSTRAP=1 cargo fmt --all -- --check

clippy:
  stage: cargo
  image: rust:1.56.1
  before_script:
    - rm rust-toolchain.toml
    - rustup component add clippy
  script:
    - RUSTC_BOOTSTRAP=1 cargo clippy -- -D warnings

debug:
  stage: cargo
  image: rust:1.56.1
  before_script:
    - rm rust-toolchain.toml
  script:
    - RUSTC_BOOTSTRAP=1 cargo build

release:
  stage: cargo
  image: rust:1.56.1
  before_script:
    - rm rust-toolchain.toml
  script:
    - RUSTC_BOOTSTRAP=1 cargo build --release
    - mv target/release/wyrcan wyrcan
    - strip ./wyrcan
  artifacts:
    paths:
      - wyrcan

build:
  stage: container
  image: docker:latest
  only: [merge_requests]
  services:
    - docker:dind
  script:
    - cp wyrcan container/wyrcan
    - chmod g-w,o-w container/*
    - docker build container/

tag:
  stage: container
  image: docker:latest
  except: [merge_requests]
  services:
    - docker:dind
  script:
    - cp wyrcan container/wyrcan
    - chmod g-w,o-w container/*
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME container/
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

images:
  stage: images
  image: debian:latest
  except: [merge_requests]
  before_script:
    - apt update
    - apt install -y mtools xorriso xz-utils ca-certificates dosfstools libarchive-tools cpio
  script:
    - ./wyrcan convert --kernel wyrcan.kernel --initrd wyrcan.initrd $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    - xz -T0 -9 -C crc32 wyrcan.initrd
    - mv wyrcan.initrd.xz wyrcan.initrd
    - ./iso.sh wyrcan.kernel wyrcan.initrd wyrcan.iso
  artifacts:
    paths:
      - wyrcan.kernel
      - wyrcan.initrd
      - wyrcan.iso
